// Generated by Wrangler by running `wrangler types`

interface Env {
	KV_NAMESPACE: KVNamespace;
	TELEGRAM_BOT_TOKEN: string;
	CHAT_ID: string;
	WORKER_URL: string;
	NODE_ENV: string;
	DB: D1Database;
}
