// Generated by Wrangler by running `wrangler types`

interface Env {
	KV_NAMESPACE: KVNamespace;
	WORKER_URL: 'https://ats-test.flutter1flow.workers.dev';
	NODE_ENV: 'production';
	TELEGRAM_BOT_TOKEN: string;
	CHAT_ID: string;
	DB: D1Database;
}
