#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if the current branch is 'main'
branch=$(git symbolic-ref --short HEAD)

if [ "$branch" = "main" ]; then
  echo "❌	Direct commits to the 'main' branch are not allowed. Please switch to a feature branch."
  exit 1
fi

# Always run lint-staged.
npx lint-staged
echo "✅ Lint-staged passed."

# Run TypeScript compilation check
echo "🔍 Checking TypeScript compilation..."
npx tsc --noEmit
echo "✅ TypeScript compilation check passed."

# Check if there are code files in the 'src' folder staged for commit.
if git diff --cached --name-only | grep -q '^src/.*\.\(ts\|js\|tsx\|jsx\)$'; then
  echo "🧪 Running tests as code files in 'src' folder are part of the commit..."
  npm test
else
  echo "✅ No code files in 'src' folder staged. Skipping tests."
fi
