#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ "$branch" = "main" ] || [ "$branch" = "dev" ]; then
  echo "❌ Direct pushes to the '$branch' branch are not allowed. Use a Pull Request instead."
  exit 1
fi

echo "✅	Push allowed for branch: $branch"
