#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if the current branch is 'main'
branch=$(git symbolic-ref --short HEAD)

#if [ "$branch" = "main" ]; then
#  echo "❌ Direct commits to the 'main' branch are not allowed. Please switch to a feature branch."
#  exit 1
#fi

npx lint-staged
npm test
