name: CI for TypeScript Project

on:
    push:
        branches:
            - "**"  # Run tests on pushes to any branch
    pull_request:
        branches:
            - main  # Run tests and checks on Pull Requests to main

jobs:
    protect:
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Block Direct Push to main Branch
              run: |
                  echo "Direct pushes to 'main' are not allowed. Use a Pull Request instead."
                  exit 1

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18  # Specify Node.js version

            - name: Install dependencies
              run: npm ci  # Use `npm install` if `package-lock.json` doesn't exist

            - name: Run tests
              run: npm test

            - name: Run TypeScript check
              run: npx tsc --noEmit
