name: CI/CD for TypeScript Project

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main
      - dev

jobs:
  Build-and-Validate:
    runs-on: ubuntu-24.04

    steps:
      - name: Validate Push to main/dev
        if: ${{ github.event_name == 'push' && github.base_ref == 'refs/heads/main' }}
        run: |
          echo "❌ Direct pushes to 'main' or 'dev' are not allowed. Use a Pull Request workflow instead."
          exit 1

      - name: Validate Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [[ "${{ github.base_ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" != "dev" ]]; then
            echo "❌ Pull requests to 'main' are only allowed from the 'dev' branch."
            exit 1
          elif [[ "${{ github.base_ref }}" == "dev" && "${{ github.event.pull_request.head.ref }}" == "main" ]]; then
            echo "❌ Pull requests to 'dev' cannot come from 'main'."
            exit 1
          else
            echo "✅ Pull request validation passed."
          fi

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-22
          lookup-only: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Run Code Quality Checks (ESLint & Prettier)
        run: npm run lint && npm run prettier:check

      - name: Run TypeScript Check
        run: npx tsc --noEmit

      - name: Run Unit Tests & Generate Coverage
        if: ${{ github.event_name == 'push' }}
        run: npm run test
