name: CI/CD for TypeScript Project

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}
          lookup-only: true # Ensures the cache is used for restore but not saved after the job

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Code Quality Checks (ESLint & Prettier)
        run: npm run lint && npm run prettier:check

      - name: Run Unit Tests
        run: npm test

      - name: Run TypeScript Check
        run: npx tsc --noEmit

      - name: Generate Coverage (Optional)
        if: ${{ github.event_name == 'push' }}
        run: npm run test -- --coverage

      - name: Upload Coverage to Codecov
        if: ${{ github.event_name == 'push' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
