name: Deploy to Cloudflare Workers

on:
    push:
        branches:
            - main # Only deploy when changes are merged to the main branch
    pull_request:
        branches:
            - main # Run tests and checks on PRs targeting main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run tests
              run: npm test

    deploy:
        needs: test
        if: github.ref == 'refs/heads/main' # Only deploy on main branch
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Wrangler CLI
              run: npm install -g wrangler

            - name: Publish to Cloudflare Workers
              env:
                  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
              run: wrangler publish
